language: node_js
sudo: false
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '4.1'
env:
  global:
    - secure: "gO9qXOPJu1xj09ICCE7S6P89vLu/HrO5nMGqXQU91N4Oi9BfMgEAu82D1qs8RjGVg3ExeKgZ8ZdSbJz7d3Rymzv5HJ7O4P94qnOq1zYMybhhIAX3b5K4E3zs0OHP91wHzInYM01W8o15L+3uBOF9DIhNqrPuD8h6ObFBAplRhko+/wq6ZILaVAe7GSh5DxA5AWFsba2cfAXIRCR+z3TNGoDheHH/6AdsDLc37TJzXt1TEEXUiMdzB3LRavsCsxTbFSBdbaBxme2Fbl0Sn0OE7odN9+4QXFBmhAe9YyFRDUneRIJO700H7DXslp8NNKOLBUgSmcpgN8y5bLHfKQhzFoAjqlFDN/ewTDhEJE72ZzLLkEv/zQPVKTJiaLTO8qJBdoQT3xTRcNiHyNtRUp1Y7DvSDBrJgNunflmKgUD+DaC/Mbb94w6AB+2EiGyCj12PDcr5EKRrPNpyI6hrockFqbG39I1I43OTTPrPmZYWcRSUKkrm4RklTQ/g8VC4lfXg9QW73hQBD0gGrzoyPG2hTNCAJNZWs4F23mnKe63aulLTtLtX/4Vc/n+oNC0GWx85es7VvOokp/PAupUe4MNdSfkSMi3cHX4OhzEJ3qmwU44gdojk6QFe13pUMf4xGWRvoxgNdn2JHx3U834uyx58KzavnprYV/QA2I6REw7R9YU="
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower gulp
  - bower i
script:
  - ./travis-runner.sh
